// urbanai-app-react/src/components/ui/spinner.tsx
import { cn } from "@/lib/utils"
import { VariantProps, cva } from "class-variance-authority"

const spinnerVariants = cva(
  "animate-spin rounded-full border-2 border-solid border-current border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite]",
  {
    variants: {
      size: {
        xs: "h-3 w-3",
        sm: "h-4 w-4", 
        md: "h-6 w-6",
        lg: "h-8 w-8",
        xl: "h-12 w-12",
      },
    },
    defaultVariants: {
      size: "md",
    },
  }
)

export interface SpinnerProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof spinnerVariants> {}

const Spinner = ({ className, size, ...props }: SpinnerProps) => {
  return (
    <div
      className={cn(spinnerVariants({ size }), className)}
      role="status"
      aria-label="Loading"
      {...props}
    />
  )
}

export { Spinner, spinnerVariants }

// urbanai-app/src/components/ui/spinner/Spinner.vue
<template>
  <div :class="cn('animate-spin rounded-full border-2 border-current border-t-transparent', className)" :style="{ width: size, height: size }" v-bind="$attrs" />
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'

interface Props {
  size?: string
  className?: string
}

withDefaults(defineProps<Props>(), {
  size: '16px',
  className: ''
})
</script>
