// urbanai-app-react/src/components/arcgis-scene-viewer.tsx
"use client";

import React, { useEffect, useRef, useState } from 'react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  ArcGISSceneViewerProps,
  EsriModules,
  GeometryResponse,
  VisualizationData,
  ProcessedFeature,
  ColorValue,
  ARCGIS_CONFIG,
  PROPERTY_COLORS,
  SURFACE_COLORS
} from '@/types/arcgis';

export default function ArcGISSceneViewer({
  gmlIds,
  apiBaseUrl = 'http://localhost:8080',
  geometryData,
  geometryLoading = false,
  className = ''
}: ArcGISSceneViewerProps) {
  const mapDiv = useRef<HTMLDivElement>(null);
  const viewRef = useRef<any>(null);
  const mapRef = useRef<any>(null);
  const esriModulesRef = useRef<EsriModules | null>(null);
  const currentDataRef = useRef<VisualizationData | null>(null);

  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedProperty, setSelectedProperty] = useState('');
  const [availableProperties, setAvailableProperties] = useState<string[]>([]);

  // Utility functions for ring orientation
  const isClockwise = (ring: number[][]) => {
    let sum = 0;
    for (let i = 0; i < ring.length - 1; i++) {
      sum += (ring[i + 1][0] - ring[i][0]) * (ring[i + 1][1] + ring[i][1]);
    }
    return sum > 0;
  };

  const reverseRing = (ring: number[][]) => [...ring].reverse();

  const fixRingOrientation = (rings: number[][][]) => {
    return rings.map((ring, index) => {
      const ringIsClockwise = isClockwise(ring);
      if (index === 0) {
        return !ringIsClockwise ? reverseRing(ring) : ring;
      } else {
        return ringIsClockwise ? reverseRing(ring) : ring;
      }
    });
  };

  // Load ArcGIS API
  const loadArcGISAPI = (): Promise<void> => {
    return new Promise((resolve, reject) => {
      if ((window as any).require) {
        resolve();
        return;
      }

      const cssLink = document.createElement('link');
      cssLink.rel = 'stylesheet';
      cssLink.href = 'https://js.arcgis.com/4.33/esri/themes/light/main.css';
      document.head.appendChild(cssLink);

      const script = document.createElement('script');
      script.src = 'https://js.arcgis.com/4.33/';
      script.onload = () => resolve();
      script.onerror = () => reject(new Error('Failed to load ArcGIS API'));
      document.head.appendChild(script);
    });
  };

  // Initialize ArcGIS modules and map
  const initializeMap = async () => {
    if (!mapDiv.current) return;

    // Ensure container has proper dimensions before initializing
    const containerRect = mapDiv.current.getBoundingClientRect();
    if (containerRect.width === 0 || containerRect.height === 0) {
      console.warn('Container has zero dimensions, waiting for proper sizing...');
      setTimeout(() => initializeMap(), 100);
      return;
    }

    try {
      const modules = await new Promise((resolve) => {
        (window as any).require([
          "esri/Map", "esri/views/SceneView", "esri/config", "esri/layers/FeatureLayer",
          "esri/widgets/Legend", "esri/widgets/LayerList", "esri/widgets/Expand", 
          "esri/widgets/Fullscreen", "esri/geometry/Extent", "esri/geometry/Point"
        ], (...loadedModules: any[]) => {
          resolve({
            Map: loadedModules[0], SceneView: loadedModules[1], esriConfig: loadedModules[2],
            FeatureLayer: loadedModules[3], Legend: loadedModules[4], LayerList: loadedModules[5],
            Expand: loadedModules[6], Fullscreen: loadedModules[7], Extent: loadedModules[8], Point: loadedModules[9]
          });
        });
      });

      esriModulesRef.current = modules as EsriModules;
      const { Map, SceneView, esriConfig, Legend, LayerList, Expand, Fullscreen } = esriModulesRef.current;

      esriConfig.apiKey = ARCGIS_CONFIG.API_KEY;

      mapRef.current = new Map({
        basemap: "arcgis/topographic",
        ground: "world-elevation"
      });

      viewRef.current = new SceneView({
        container: mapDiv.current,
        map: mapRef.current,
        camera: {
          position: { x: 11.5820, y: 48.1351, z: 1000 },
          tilt: 45,
          heading: 180
        },
        environment: {
          lighting: { directShadowsEnabled: true }
        }
      });

      await viewRef.current.when();

      // Add widgets (removed deprecated Fullscreen widget)
      const legend = new Legend({ view: viewRef.current });
      const layerList = new LayerList({ view: viewRef.current });

      const legendExpand = new Expand({
        view: viewRef.current,
        content: legend,
        expandIconClass: "esri-icon-layer-list",
        group: "top-right"
      });

      const layerListExpand = new Expand({
        view: viewRef.current,
        content: layerList,
        expandIconClass: "esri-icon-layers", 
        group: "top-right"
      });

      viewRef.current.ui.add([legendExpand, layerListExpand], "top-right");

      // Add click handler for popups
      viewRef.current.on("click", (event: any) => {
        viewRef.current.hitTest(event).then((response: any) => {
          const results = response.results.filter((result: any) => 
            result.graphic.layer.type === "feature"
          );
          if (results.length > 0) {
            viewRef.current.popup.open({
              location: event.mapPoint,
              features: [results[0].graphic]
            });
          }
        });
      });

      setIsLoading(false);
    } catch (err) {
      setError(`Failed to initialize map: ${err instanceof Error ? err.message : 'Unknown error'}`);
      setIsLoading(false);
    }
  };

  // Zoom to data extent
  const zoomToData = async (data: { adiabaticData: any, shadingData: any }) => {
    if (!viewRef.current || !esriModulesRef.current) return;

    const { Extent, Point } = esriModulesRef.current;
    let allCoordinates: number[][] = [];

    [data.adiabaticData, data.shadingData].forEach(dataset => {
      dataset?.features?.forEach((feature: any) => {
        if (feature.geometry?.coordinates) {
          if (feature.geometry.type === 'Polygon') {
            allCoordinates = allCoordinates.concat(feature.geometry.coordinates[0]);
          } else if (feature.geometry.type === 'MultiPolygon') {
            feature.geometry.coordinates.forEach((polygon: any) => {
              allCoordinates = allCoordinates.concat(polygon[0]);
            });
          }
        }
      });
    });

    if (allCoordinates.length > 0) {
      const xCoords = allCoordinates.map(coords => coords[0]);
      const yCoords = allCoordinates.map(coords => coords[1]);
      
      const extent = new Extent({
        xmin: Math.min(...xCoords), ymin: Math.min(...yCoords),
        xmax: Math.max(...xCoords), ymax: Math.max(...yCoords),
        spatialReference: { wkid: 4326 }
      });

      const centerX = (extent.xmin + extent.xmax) / 2;
      const centerY = (extent.ymin + extent.ymax) / 2;
      const maxExtent = Math.max(extent.xmax - extent.xmin, extent.ymax - extent.ymin);
      
      await viewRef.current.goTo({
        target: new Point({
          x: centerX, y: centerY,
          spatialReference: { wkid: 4326 }
        }),
        tilt: 60, heading: 45,
        zoom: maxExtent < 0.001 ? 19 : 18
      }, { duration: 3000, easing: "ease-in-out" });
    }
  };

  // Create feature layer
  const createFeatureLayer = (features: any[], title: string, color: string | number[], properties: any) => {
    if (!esriModulesRef.current) return null;
    const { FeatureLayer } = esriModulesRef.current;
    
    return new FeatureLayer({
      source: features,
      objectIdField: "ObjectID",
      title,
      fields: [
        { name: "ObjectID", alias: "ObjectID", type: "oid" },
        ...Object.keys(properties || {}).map((prop: string) => ({
          name: prop, alias: prop, type: "string"
        }))
      ],
      renderer: {
        type: "simple",
        symbol: {
          type: "polygon-3d",
          symbolLayers: [{
            type: "fill",
            material: { color, colorMixMode: "replace" },
            outline: { color: [255, 255, 255, 1.0], size: "2px" }
          }]
        }
      },
      popupTemplate: {
        title,
        content: [{
          type: "fields",
          fieldInfos: Object.keys(properties || {}).map((prop: string) => ({
            fieldName: prop, label: prop
          }))
        }]
      }
    });
  };

  // Process geometry data
  const processGeometryData = async (data: any) => {
    if (!viewRef.current || !mapRef.current || !esriModulesRef.current) {
      console.error('Scene not properly initialized');
      return;
    }

    try {
      console.log('Processing geometry data:', data);
      
      // Ensure view is ready
      if (!viewRef.current.ready) {
        await viewRef.current.when();
      }

      // Clear existing layers safely
      try {
        mapRef.current.layers.removeAll();
      } catch (layerError) {
        console.warn('Error removing layers:', layerError);
      }

      let geometryData = data.results || data;
      let adiabaticData: any = null;
      let shadingData: any = null;

      // Extract data from nested structure
      if (geometryData.surfaces_adiabatic) {
        adiabaticData = geometryData.surfaces_adiabatic;
      } else {
        for (const key in geometryData) {
          if (geometryData[key]?.surfaces_adiabatic) {
            adiabaticData = geometryData[key].surfaces_adiabatic;
            break;
          }
        }
      }

      if (geometryData.shading_surfaces) {
        shadingData = geometryData.shading_surfaces;
      } else {
        for (const key in geometryData) {
          if (geometryData[key]?.shading_surfaces) {
            shadingData = geometryData[key].shading_surfaces;
            break;
          }
        }
      }

      console.log('Extracted data:', { adiabaticData, shadingData });
      currentDataRef.current = { adiabaticData, shadingData };

      // Set up property picker
      if (adiabaticData?.features?.length > 0) {
        const properties = Object.keys(adiabaticData.features[0].properties);
        setAvailableProperties(properties);
        if (!selectedProperty && properties.length > 0) {
          setSelectedProperty(properties[0]);
        }
      }

      // Add shading surfaces
      if (shadingData?.features?.length > 0) {
        console.log('Processing shading surfaces:', shadingData.features.length);
        try {
          const shadingFeatures = shadingData.features.map((feature: any, index: number) => {
            let rings = feature.geometry.coordinates;
            if (feature.geometry.type === 'Polygon') {
              rings = feature.geometry.coordinates;
            } else if (feature.geometry.type === 'MultiPolygon') {
              rings = feature.geometry.coordinates.flat();
            }
            
            return {
              geometry: {
                type: "polygon",
                rings: fixRingOrientation(rings),
                spatialReference: { wkid: 4326 }
              },
              attributes: { ObjectID: index, ...feature.properties }
            };
          });

          const shadingLayer = createFeatureLayer(
            shadingFeatures, 
            "Shading Surfaces", 
            [128, 128, 128, 0.7], 
            shadingData.features[0]?.properties
          );
          
          if (shadingLayer) {
            mapRef.current.add(shadingLayer);
            console.log('Added shading layer successfully');
          }
        } catch (shadingError) {
          console.error('Error processing shading surfaces:', shadingError);
        }
      }

      // Add adiabatic surfaces
      if (adiabaticData?.features?.length > 0) {
        console.log('Processing adiabatic surfaces:', adiabaticData.features.length);
        try {
          if (selectedProperty) {
            visualizeByProperty(selectedProperty);
          } else {
            const adiabaticFeatures = adiabaticData.features.map((feature: any, index: number) => {
              let rings = feature.geometry.coordinates;
              if (feature.geometry.type === 'Polygon') {
                rings = feature.geometry.coordinates;
              } else if (feature.geometry.type === 'MultiPolygon') {
                rings = feature.geometry.coordinates.flat();
              }
              
              return {
                geometry: {
                  type: "polygon",
                  rings: fixRingOrientation(rings),
                  spatialReference: { wkid: 4326 }
                },
                attributes: { ObjectID: index, ...feature.properties }
              };
            });

            const adiabaticLayer = createFeatureLayer(
              adiabaticFeatures, 
              "Adiabatic Surfaces", 
              [255, 100, 100, 0.8], 
              adiabaticData.features[0]?.properties
            );
            
            if (adiabaticLayer) {
              mapRef.current.add(adiabaticLayer);
              console.log('Added adiabatic layer successfully');
            }
          }
        } catch (adiabaticError) {
          console.error('Error processing adiabatic surfaces:', adiabaticError);
        }
      }

      // Only zoom if we have data
      if (adiabaticData || shadingData) {
        try {
          await zoomToData({ adiabaticData, shadingData });
        } catch (zoomError) {
          console.warn('Error zooming to data:', zoomError);
        }
      }
      
      console.log('Geometry processing completed successfully');
    } catch (err) {
      console.error('Error in processGeometryData:', err);
      throw err; // Re-throw to be handled by the calling useEffect
    }
  };

  // Visualize by property
  const visualizeByProperty = (property: string) => {
    if (!currentDataRef.current?.adiabaticData || !mapRef.current) return;

    const { adiabaticData } = currentDataRef.current;
    
    // Clear and re-add shading surfaces first
    mapRef.current.layers.removeAll();
    
    if (currentDataRef.current.shadingData?.features && currentDataRef.current.shadingData.features.length > 0) {
      const shadingFeatures = currentDataRef.current.shadingData.features.map((feature: any, index: number) => ({
        geometry: {
          type: "polygon",
          rings: fixRingOrientation(
            feature.geometry.type === 'Polygon' 
              ? feature.geometry.coordinates 
              : feature.geometry.coordinates.flat()
          ),
          spatialReference: { wkid: 4326 }
        },
        attributes: { ObjectID: index, ...feature.properties }
      }));

      const shadingLayer = createFeatureLayer(
        shadingFeatures, 
        "Shading Surfaces", 
        [...SURFACE_COLORS.SHADING], 
        currentDataRef.current.shadingData.features[0]?.properties
      );
      if (shadingLayer) {
        mapRef.current.add(shadingLayer);
      }
    }

    // Group adiabatic features by property value
    const features = adiabaticData.features.map((feature: any, index: number) => ({
      geometry: {
        type: "polygon",
        rings: fixRingOrientation(
          feature.geometry.type === 'Polygon' 
            ? feature.geometry.coordinates 
            : feature.geometry.coordinates.flat()
        ),
        spatialReference: { wkid: 4326 }
      },
      attributes: {
        ObjectID: index,
        featureProp: feature.properties[property],
        ...feature.properties
      }
    }));

    const uniqueValues = [...new Set(features.map((f: any) => f.attributes.featureProp))].filter(val => val != null);

    uniqueValues.forEach((value, index) => {
      const sublayerFeatures = features.filter((f: any) => f.attributes.featureProp === value);
      const layer = createFeatureLayer(
        sublayerFeatures, 
        String(value), 
        PROPERTY_COLORS[index % PROPERTY_COLORS.length], 
        adiabaticData.features[0].properties
      );
      if (layer) {
        mapRef.current.add(layer);
      }
    });
  };

  // Handle property change
  const handlePropertyChange = (property: string) => {
    setSelectedProperty(property);
    if (currentDataRef.current) {
      visualizeByProperty(property);
    }
  };

  // Initialize component
  useEffect(() => {
    const initialize = async () => {
      try {
        await loadArcGISAPI();
        await initializeMap();
      } catch (err) {
        setError(`Initialization failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
        setIsLoading(false);
      }
    };

    initialize();

    return () => {
      if (viewRef.current) {
        viewRef.current.destroy();
      }
    };
  }, []);

  // Process geometry data when it changes
  useEffect(() => {
    const processData = async () => {
      if (geometryData && viewRef.current && mapRef.current && !isLoading && esriModulesRef.current) {
        try {
          // Ensure view is fully ready before processing
          await viewRef.current.when();
          await processGeometryData(geometryData);
        } catch (err) {
          console.error('Error processing geometry data:', err);
          setError(`Failed to process geometry data: ${err instanceof Error ? err.message : 'Unknown error'}`);
        }
      }
    };

    processData();
  }, [geometryData, isLoading]);

  if (error) {
    return (
      <Card className={`p-6 ${className}`}>
        <div className="text-center text-red-600">
          <h3 className="text-lg font-semibold mb-2">Error Loading Scene</h3>
          <p>{error}</p>
        </div>
      </Card>
    );
  }

  return (
    <Card className={`flex flex-col ${className}`}>
      {/* Property Selector */}
      {availableProperties.length > 0 && (
        <div className="p-4 border-b">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-medium">Property:</span>
            {availableProperties.map((property) => (
              <Badge
                key={property}
                variant={selectedProperty === property ? "default" : "outline"}
                className="cursor-pointer"
                onClick={() => handlePropertyChange(property)}
              >
                {property}
              </Badge>
            ))}
          </div>
        </div>
      )}

      {/* Scene Container */}
      <div className="flex-1 relative min-h-[500px]">
        {isLoading && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-50 z-10">
            <div className="text-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto mb-2"></div>
              <p className="text-sm text-gray-600">Loading ArcGIS Scene Viewer...</p>
            </div>
          </div>
        )}
        
        {geometryLoading && (
          <div className="absolute top-4 left-4 bg-white rounded-lg shadow-lg p-3 z-20">
            <div className="flex items-center gap-2">
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
              <span className="text-sm">Loading geometry data...</span>
            </div>
          </div>
        )}

        <div 
          ref={mapDiv} 
          className="w-full h-full"
          style={{ minHeight: '500px' }}
        />
      </div>
    </Card>
  );
}

// urbanai-frontend/src/components/map/ArcGISSceneViewer.vue
<template>
  <div class="scene-viewer-container">
    <!-- ArcGIS Scene View Container -->
    <div id="viewDiv" class="map-container"></div>
    
    <!-- Calcite Property Picker Panel (hidden, will be added to ArcGIS UI) -->
    <calcite-panel id="pickerContainer" heading="Select Feature Property" width-scale="l" height-scale="l" style="display: none;">
      <div class="panel-content">
        <calcite-combobox id="featurePicker" placeholder="Pick a Feature Property" selection-mode="single">
        </calcite-combobox>
      </div>
    </calcite-panel>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, toRefs } from 'vue'

// Props
interface Props {
  gmlIds: string[]
  apiBaseUrl?: string
  geometryData?: any
  geometryLoading?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  apiBaseUrl: 'http://localhost:8080',
  geometryData: null,
  geometryLoading: false
})

const { gmlIds, apiBaseUrl, geometryData, geometryLoading } = toRefs(props)

// Reactive variables
const error = ref('')
const selectedProperty = ref('')
const availableProperties = ref<string[]>([])

// ArcGIS related variables
let view: any = null
let map: any = null
let esriModules: any = {}

// Store the current data for re-rendering when property changes
let currentData: { adiabaticData: any, shadingData: any } | null = null

// Color palette for different property values (from original HTML)
const colors = ["#fc3e5aff", "#fce138ff", "#4c81cdff", "#f1983cff", "#48885cff", "#a553b7ff", "#fff799ff", "#b1a9d0ff", "#6ecffcff", "#fc6f84ff", "#6af689ff", "#fcd27eff"]

// Function to calculate if a ring is clockwise or counter-clockwise
const isClockwise = (ring: number[][]) => {
  let sum = 0
  for (let i = 0; i < ring.length - 1; i++) {
    sum += (ring[i + 1][0] - ring[i][0]) * (ring[i + 1][1] + ring[i][1])
  }
  return sum > 0
}

// Function to reverse a ring's direction
const reverseRing = (ring: number[][]) => {
  return [...ring].reverse()
}

// Function to fix ring orientation for ArcGIS
// ArcGIS expects: exterior rings clockwise, holes counter-clockwise
// GeoJSON has: exterior rings counter-clockwise, holes clockwise
const fixRingOrientation = (rings: number[][][]) => {
  return rings.map((ring, index) => {
    const ringIsClockwise = isClockwise(ring)
    
    if (index === 0) {
      // Exterior ring should be clockwise for ArcGIS
      if (!ringIsClockwise) {
        
        return reverseRing(ring)
      }
    } else {
      // Interior rings (holes) should be counter-clockwise for ArcGIS
      if (ringIsClockwise) {

        return reverseRing(ring)
      }
    }
    
    return ring
  })
}

// API Response interfaces
interface GeometryResponse {
  [key: string]: any // Allow dynamic keys since the structure is nested
}

// Watch for changes in geometry data and process it automatically
watch(geometryData, async (newGeometryData) => {
  if (newGeometryData && view && map) {
    await processGeometryData(newGeometryData)
  }
}, { immediate: false })

// Process geometry data and display in ArcGIS
const processGeometryData = async (data: GeometryResponse) => {
  if (!view || !map) {
    error.value = 'Map not initialized'
    return
  }

  if (!view.ready) {
    await view.when()
  }

  const { FeatureLayer } = esriModules

  try {
    // Clear existing layers
    map.layers.removeAll()

    // Check if data is wrapped in 'results' property
    let geometryData = data
    if (data.results) {
      geometryData = data.results
    }

    // Extract surfaces_adiabatic from nested structure
    let adiabaticData: any = null
    let shadingData: any = null

    // Look for surfaces_adiabatic in the response structure
    if (geometryData.surfaces_adiabatic) {
      adiabaticData = geometryData.surfaces_adiabatic
    } else {
      // Check if it's nested in results or other structure
      for (const key in geometryData) {
        if (geometryData[key] && geometryData[key].surfaces_adiabatic) {
          adiabaticData = geometryData[key].surfaces_adiabatic
          break
        }
      }
    }

    // Look for shading_surfaces in the response structure
    if (geometryData.shading_surfaces) {
      shadingData = geometryData.shading_surfaces
    } else {
      // Check if it's nested in results or other structure
      for (const key in geometryData) {
        if (geometryData[key] && geometryData[key].shading_surfaces) {
          shadingData = geometryData[key].shading_surfaces
          break
        }
      }
    }

    // If no data found, let's see what's available
    if (!adiabaticData && !shadingData) {
      for (const key in geometryData) {
        // Silently check data structure
      }
    }

    // Store current data for property visualization
    currentData = { adiabaticData, shadingData }

    // Set up property picker if we have adiabatic data
    if (adiabaticData && adiabaticData.features && adiabaticData.features.length > 0) {
      // Get property names for picker
      availableProperties.value = Object.keys(adiabaticData.features[0].properties)
      
      // Set up Calcite UI components
      setupPropertyPicker()
      
      // Set default property
      if (!selectedProperty.value && availableProperties.value.length > 0) {
        selectedProperty.value = availableProperties.value[0]
      }
    }

    // Add shading surfaces (always visible)
    if (shadingData && shadingData.features && shadingData.features.length > 0) {
      const shadingFeatures = shadingData.features.map((feature: any, index: number) => ({
        geometry: {
          type: "polygon",
          rings: (() => {
            let rings = feature.geometry.coordinates
            if (feature.geometry.type === 'Polygon') {
              rings = feature.geometry.coordinates
              if (rings.length > 1) {
                // Has interior rings (holes)
              }
            } else if (feature.geometry.type === 'MultiPolygon') {
              rings = feature.geometry.coordinates.flat()
            }
            
            // Fix ring orientation for ArcGIS
            rings = fixRingOrientation(rings)
            
            return rings
          })(),
          spatialReference: { wkid: 4326 }
        },
        attributes: {
          ObjectID: index,
          ...feature.properties
        }
      }))

      try {
        const shadingLayer = new FeatureLayer({
          source: shadingFeatures,
          objectIdField: "ObjectID",
          title: "Shading Surfaces",
          fields: [
            { name: "ObjectID", alias: "ObjectID", type: "oid" },
            ...Object.keys(shadingData.features[0]?.properties || {}).map((prop: string) => ({
              name: prop,
              alias: prop,
              type: "string"
            }))
          ],
          renderer: {
            type: "simple",
            symbol: {
              type: "polygon-3d",
              symbolLayers: [{
                type: "fill",
                material: { 
                  color: [128, 128, 128, 0.7],
                  colorMixMode: "replace"
                },
                outline: {
                  color: [255, 255, 255, 1.0],
                  size: "2px"
                }
              }]
            }
          },
          popupTemplate: {
            title: "Shading Surface",
            content: [{
              type: "fields",
              fieldInfos: Object.keys(shadingData.features[0]?.properties || {}).map((prop: string) => ({
                fieldName: prop,
                label: prop
              }))
            }]
          }
        })

        map.add(shadingLayer)
      } catch (layerError) {
        console.error('❌ Error creating shading layer:', layerError)
      }
    }

    // If we have a selected property, visualize by that property
    if (selectedProperty.value && adiabaticData) {
      visualizeByProperty(selectedProperty.value)
    } else if (adiabaticData && adiabaticData.features && adiabaticData.features.length > 0) {
      // Otherwise show default red adiabatic surfaces
      const adiabaticFeatures = adiabaticData.features.map((feature: any, index: number) => {        
        // Handle GeoJSON polygon coordinates properly
        let rings = feature.geometry.coordinates
        if (feature.geometry.type === 'Polygon') {
          rings = feature.geometry.coordinates
          if (rings.length > 1) {
            // Has interior rings (holes)
          }
        } else if (feature.geometry.type === 'MultiPolygon') {
          rings = feature.geometry.coordinates.flat()
        }
        
        // Fix ring orientation for ArcGIS
        rings = fixRingOrientation(rings)
        
        return {
          geometry: {
            type: "polygon",
            rings: rings,
            spatialReference: { wkid: 4326 }
          },
          attributes: {
            ObjectID: index,
            ...feature.properties
          }
        }
      })

      try {
        const adiabaticLayer = new FeatureLayer({
          source: adiabaticFeatures,
          objectIdField: "ObjectID",
          title: "Adiabatic Surfaces",
          fields: [
            { name: "ObjectID", alias: "ObjectID", type: "oid" },
            ...Object.keys(adiabaticData.features[0]?.properties || {}).map((prop: string) => ({
              name: prop,
              alias: prop,
              type: "string"
            }))
          ],
          renderer: {
            type: "simple",
            symbol: {
              type: "polygon-3d",
              symbolLayers: [{
                type: "fill",
                material: { 
                  color: [255, 100, 100, 0.8],
                  colorMixMode: "replace"
                },
                outline: {
                  color: [255, 255, 255, 1.0],
                  size: "2px"
                }
              }]
            }
          },
          popupTemplate: {
            title: "Adiabatic Surface",
            content: [{
              type: "fields",
              fieldInfos: Object.keys(adiabaticData.features[0]?.properties || {}).map((prop: string) => ({
                fieldName: prop,
                label: prop
              }))
            }]
          }
        })

        map.add(adiabaticLayer)
      } catch (layerError) {
        console.error('❌ Error creating adiabatic layer:', layerError)
      }
    }

    // Calculate extent and zoom to data
    await zoomToData({ adiabaticData, shadingData })

  } catch (err) {
    error.value = `Failed to process geometry data: ${err instanceof Error ? err.message : 'Unknown error'}`
    console.error('Processing error:', err)
  }
}

// Setup Calcite property picker UI
const setupPropertyPicker = () => {
  const featurePicker = document.getElementById("featurePicker") as any
  const pickerContainer = document.getElementById("pickerContainer")
  
  if (!featurePicker || !pickerContainer) return

  // Clear existing items
  featurePicker.innerHTML = ''

  // Add property options
  availableProperties.value.forEach(prop => {
    const item = document.createElement("calcite-combobox-item") as any
    item.value = prop
    item.setAttribute('text-label', prop)
    item.innerHTML = prop
    featurePicker.appendChild(item)
  })

  // Add event listener for property changes
  featurePicker.addEventListener("calciteComboboxChange", (event: any) => {
    const selectedValue = event.target.selectedItems[0]?.value
    if (selectedValue) {
      selectedProperty.value = selectedValue
      onPropertyChange()
    }
  })

  // Show the picker container
  pickerContainer.style.display = 'block'
}

// Calculate extent and zoom to data
const zoomToData = async (data: { adiabaticData: any, shadingData: any }) => {
  const { Extent, Point } = esriModules
  
  let allCoordinates: number[][] = []

  // Collect all coordinates from GeoJSON features
  if (data.adiabaticData?.features) {
    data.adiabaticData.features.forEach((feature: any) => {
      if (feature.geometry?.coordinates) {
        // Handle different geometry types
        if (feature.geometry.type === 'Polygon') {
          // For polygons, coordinates[0] is the exterior ring
          allCoordinates = allCoordinates.concat(feature.geometry.coordinates[0])
        } else if (feature.geometry.type === 'MultiPolygon') {
          // For multipolygons, iterate through all polygons
          feature.geometry.coordinates.forEach((polygon: any) => {
            allCoordinates = allCoordinates.concat(polygon[0])
          })
        }
      }
    })
  }

  if (data.shadingData?.features) {
    data.shadingData.features.forEach((feature: any) => {
      if (feature.geometry?.coordinates) {
        // Handle different geometry types
        if (feature.geometry.type === 'Polygon') {
          // For polygons, coordinates[0] is the exterior ring
          allCoordinates = allCoordinates.concat(feature.geometry.coordinates[0])
        } else if (feature.geometry.type === 'MultiPolygon') {
          // For multipolygons, iterate through all polygons
          feature.geometry.coordinates.forEach((polygon: any) => {
            allCoordinates = allCoordinates.concat(polygon[0])
          })
        }
      }
    })
  }

  if (allCoordinates.length > 0) {
    const xCoords = allCoordinates.map(coords => coords[0])
    const yCoords = allCoordinates.map(coords => coords[1])
    
    const extent = new Extent({
      xmin: Math.min(...xCoords),
      ymin: Math.min(...yCoords),
      xmax: Math.max(...xCoords),
      ymax: Math.max(...yCoords),
      spatialReference: { wkid: 4326 }
    })

    // Calculate center point for better camera positioning
    const centerX = (extent.xmin + extent.xmax) / 2
    const centerY = (extent.ymin + extent.ymax) / 2
    
    // Calculate appropriate zoom level based on extent size
    const extentWidth = extent.xmax - extent.xmin
    const extentHeight = extent.ymax - extent.ymin
    const maxExtent = Math.max(extentWidth, extentHeight)
    
    // For building-level viewing, use a much closer zoom
    const altitude = maxExtent < 0.001 ? 50 : maxExtent * 12000
    
    // Animate view to the building with closer zoom
    await view.goTo({
      target: new Point({
        x: centerX,
        y: centerY,
        spatialReference: { wkid: 4326 }
      }),
      tilt: 60,
      heading: 45,
      zoom: maxExtent < 0.001 ? 19 : 18
    }, {
      duration: 3000,
      easing: "ease-in-out"
    })
  }
}

// Handle property selection change
const onPropertyChange = () => {
  if (selectedProperty.value && currentData) {
    visualizeByProperty(selectedProperty.value)
  }
}

// Visualize adiabatic surfaces by selected property with different colors
const visualizeByProperty = (selectedProperty: string) => {
  if (!currentData || !view || !map) return

  const { FeatureLayer } = esriModules
  const { adiabaticData, shadingData } = currentData

  try {
    // Clear existing layers
    map.layers.removeAll()

    // Re-add shading surfaces (unchanged)
    if (shadingData && shadingData.features && shadingData.features.length > 0) {
      const shadingFeatures = shadingData.features.map((feature: any, index: number) => ({
        geometry: {
          type: "polygon",
          rings: (() => {
            let rings = feature.geometry.coordinates
            if (feature.geometry.type === 'Polygon') {
              rings = feature.geometry.coordinates
              if (rings.length > 1) {
                // Has interior rings (holes)
              }
            } else if (feature.geometry.type === 'MultiPolygon') {
              rings = feature.geometry.coordinates.flat()
            }
            
            // Fix ring orientation for ArcGIS
            rings = fixRingOrientation(rings)
            
            return rings
          })(),
          spatialReference: { wkid: 4326 }
        },
        attributes: {
          ObjectID: index,
          ...feature.properties
        }
      }))

      const shadingLayer = new FeatureLayer({
        source: shadingFeatures,
        objectIdField: "ObjectID",
        title: "Shading Surfaces",
        fields: [
          { name: "ObjectID", alias: "ObjectID", type: "oid" },
          ...Object.keys(shadingData.features[0]?.properties || {}).map((prop: string) => ({
            name: prop,
            alias: prop,
            type: "string"
          }))
        ],
        renderer: {
          type: "simple",
          symbol: {
            type: "polygon-3d",
            symbolLayers: [{
              type: "fill",
              material: { 
                color: [128, 128, 128, 0.7],
                colorMixMode: "replace"
              },
              outline: {
                color: [255, 255, 255, 1.0],
                size: "2px"
              }
            }]
          }
        },
        popupTemplate: {
          title: "Shading Surface",
          content: [{
            type: "fields",
            fieldInfos: Object.keys(shadingData.features[0]?.properties || {}).map((prop: string) => ({
              fieldName: prop,
              label: prop
            }))
          }]
        }
      })

      map.add(shadingLayer)
    }

    // Process adiabatic surfaces by property value
    if (adiabaticData && adiabaticData.features && adiabaticData.features.length > 0) {
      // Create base features with selected property
      const features = adiabaticData.features.map((feature: any, index: number) => ({
        geometry: {
          type: "polygon",
          rings: (() => {
            let rings = feature.geometry.coordinates
            if (feature.geometry.type === 'Polygon') {
              rings = feature.geometry.coordinates
            } else if (feature.geometry.type === 'MultiPolygon') {
              rings = feature.geometry.coordinates.flat()
            }
            
            // Fix ring orientation for ArcGIS
            rings = fixRingOrientation(rings)
            
            return rings
          })(),
          spatialReference: { wkid: 4326 }
        },
        attributes: {
          ObjectID: index,
          featureProp: feature.properties[selectedProperty],
          ...feature.properties
        }
      }))

      // Get unique values for the selected property
      const uniqueValues = [...new Set(features.map((f: any) => f.attributes.featureProp))].filter((val: any) => val != null)

      // Create a separate layer for each unique value
      const sublayers = uniqueValues.map((value, index) => {
        const sublayerFeatures = features.filter((f: any) => f.attributes.featureProp === value)

        return new FeatureLayer({
          source: sublayerFeatures,
          objectIdField: "ObjectID",
          title: String(value),
          fields: [
            { name: "ObjectID", alias: "ObjectID", type: "oid" },
            { name: "featureProp", alias: "featureProp", type: "string" },
            ...Object.keys(adiabaticData.features[0].properties).map((prop: string) => ({
              name: prop,
              alias: prop,
              type: "string"
            }))
          ],
          renderer: {
            type: "simple",
            symbol: {
              type: "polygon-3d",
              symbolLayers: [{
                type: "fill",
                material: { 
                  color: colors[index % colors.length],
                  colorMixMode: "replace"
                },
                outline: {
                  color: [255, 255, 255, 0.7],
                  size: "2px"
                }
              }]
            }
          },
          popupTemplate: {
            title: `{${selectedProperty}}`,
            content: [{
              type: "fields",
              fieldInfos: Object.keys(adiabaticData.features[0].properties).map((prop: string) => ({
                fieldName: prop,
                label: prop
              }))
            }]
          }
        })
      })

      // Add all sublayers to the map
      sublayers.forEach(layer => map.add(layer))
    }

  } catch (err) {
    error.value = `Failed to visualize by property: ${err instanceof Error ? err.message : 'Unknown error'}`
    console.error('Property visualization error:', err)
  }
}

// Initialize ArcGIS Map
const initializeMap = async () => {
  try {
    const modules = await new Promise((resolve) => {
      (window as any).require([
        "esri/Map",
        "esri/views/SceneView", 
        "esri/config",
        "esri/layers/FeatureLayer",
        "esri/widgets/Legend",
        "esri/widgets/LayerList",
        "esri/widgets/Expand",
        "esri/widgets/Fullscreen",
        "esri/geometry/Extent",
        "esri/geometry/Point",
        "esri/widgets/DirectLineMeasurement3D"
      ], (
        Map: any, 
        SceneView: any, 
        esriConfig: any, 
        FeatureLayer: any,
        Legend: any, 
        LayerList: any,
        Expand: any,
        Fullscreen: any,
        Extent: any,
        Point: any,
        DirectLineMeasurement3D: any
      ) => {
        resolve({
          Map,
          SceneView,
          esriConfig,
          FeatureLayer,
          Legend,
          LayerList,
          Expand,
          Fullscreen,
          Extent,
          Point,
          DirectLineMeasurement3D
        })
      })
    })

    esriModules = modules as any
    const { Map, SceneView, esriConfig, Legend, LayerList, Expand, Fullscreen } = esriModules

    // Set API key
    esriConfig.apiKey = "AAPK88646347a11d4ca190ec0b00201dc26c8kkfPaCG_kMmrxHsdUiVFuQzgCpecnrd664al4gHRq3VIIKlSV1epDVbEdh7tNJG"

    // Create map
    map = new Map({
      basemap: "arcgis/topographic",
      ground: "world-elevation"
    })

    // Create scene view
    view = new SceneView({
      container: "viewDiv",
      map: map,
      camera: {
        position: {
          x: 11.5820,
          y: 48.1351,
          z: 1000
        },
        tilt: 45,
        heading: 180
      },
      environment: {
        lighting: {
          directShadowsEnabled: true
        }
      }
    })

    // Wait for view to be ready
    await view.when()

    // Add widgets
    const legend = new Legend({ view })
    const layerList = new LayerList({ view })
    const fullscreen = new Fullscreen({ view })

    const legendExpand = new Expand({
      view,
      content: legend,
      expandIconClass: "esri-icon-layer-list",
      group: "top-right"
    })

    const layerListExpand = new Expand({
      view,
      content: layerList,
      expandIconClass: "esri-icon-layers", 
      group: "top-right"
    })

    // Add property picker expand widget
    const pickerContainer = document.getElementById("pickerContainer")
    const pickerExpand = new Expand({
      view,
      content: pickerContainer,
      expandIconClass: "esri-icon-filter",
      group: "top-right"
    })

    view.ui.add([legendExpand, layerListExpand, pickerExpand, fullscreen], "top-right")

    // Add click handler for popups
    view.on("click", (event: any) => {
      view.hitTest(event).then((response: any) => {
        const results = response.results.filter((result: any) => {
          return result.graphic.layer.type === "feature"
        })
        if (results.length > 0) {
          const graphic = results[0].graphic
          view.popup.open({
            location: event.mapPoint,
            features: [graphic]
          })
        }
      })
    })

  } catch (err) {
    error.value = `Failed to initialize map: ${err instanceof Error ? err.message : 'Unknown error'}`
    console.error('❌ Map initialization error:', err)
  }
}

// Load ArcGIS API
const loadArcGISAPI = () => {
  return new Promise((resolve, reject) => {
    if ((window as any).require) {
      resolve(true)
      return
    }

    // Load CSS
    const cssLink = document.createElement('link')
    cssLink.rel = 'stylesheet'
    cssLink.href = 'https://js.arcgis.com/4.29/esri/themes/light/main.css'
    document.head.appendChild(cssLink)

    // Load Calcite CSS
    const calciteCss = document.createElement('link')
    calciteCss.rel = 'stylesheet'
    calciteCss.href = 'https://js.arcgis.com/calcite-components/2.9.0/calcite.css'
    document.head.appendChild(calciteCss)

    // Load JavaScript
    const script = document.createElement('script')
    script.src = 'https://js.arcgis.com/4.29/'
    script.onload = () => resolve(true)
    script.onerror = () => reject(new Error('Failed to load ArcGIS API'))
    document.head.appendChild(script)

    // Load Calcite Components
    const calciteScript = document.createElement('script')
    calciteScript.type = 'module'
    calciteScript.src = 'https://js.arcgis.com/calcite-components/2.9.0/calcite.esm.js'
    document.head.appendChild(calciteScript)
  })
}

// Component lifecycle
onMounted(async () => {
  try {
    await loadArcGISAPI()
    await initializeMap()
    
    // Auto-process geometry if data is available
    if (geometryData.value) {
      await processGeometryData(geometryData.value)
    }
  } catch (err) {
    error.value = `Initialization failed: ${err instanceof Error ? err.message : 'Unknown error'}`
    console.error('❌ Initialization error:', err)
  }
})

onUnmounted(() => {
  if (view) {
    view.destroy()
  }
})
</script>

<style scoped>
.scene-viewer-container {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.map-container {
  flex: 1;
  width: 100%;
  height: 100%;
  min-height: 0;
}

.panel-content {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 2px;
  width: 330px;
  height: 300px;
}

calcite-combobox {
  --calcite-ui-height: 10rem;
}

calcite-combobox-item {
  height: 3rem;
  line-height: 3rem;
}

calcite-combobox-item::part(container) {
  max-height: 400px;
  overflow-y: auto;
}

/* Global styles for ArcGIS */
:global(.esri-widget) {
  font-family: inherit;
}

/* Ensure calcite dropdowns can extend outside container */
:global(.calcite-combobox-list) {
  z-index: 9999 !important;
}

:global(.calcite-popover) {
  z-index: 9999 !important;
}

:global(.esri-expand__content) {
  z-index: 1000 !important;
}

/* Allow overflow for dropdowns */
:global(.esri-expand__content-panel) {
  overflow: visible !important;
}
</style>
