// urbanai-app-react/src/components/login-page.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { useAuth } from '@/hooks/use-auth'

export default function LoginPage() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const { login, isLoading, error } = useAuth()

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    await login({ username, password })
  }

  return (
    <div className="min-h-screen flex">
      {/* Left side - Login form */}
      <div className="flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8">
        <Card className="max-w-md w-full">
          <CardHeader className="text-center">
            <CardTitle className="text-3xl font-bold text-gray-900 dark:text-white">
              Welcome to DeCO<sub className="text-2xl">two</sub>
            </CardTitle>
            <CardDescription>
              Sign in to your account to continue
            </CardDescription>
          </CardHeader>
          
          <CardContent>
            <form onSubmit={handleLogin} className="space-y-6">
              <div className="space-y-4">
                <div>
                  <Label htmlFor="username">Username</Label>
                  <Input
                    id="username"
                    type="text"
                    value={username}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => setUsername(e.target.value)}
                    autoComplete="username"
                    required
                    placeholder="Enter your username"
                    disabled={isLoading}
                  />
                </div>

                <div>
                  <Label htmlFor="password">Password</Label>
                  <Input
                    id="password"
                    type="password"
                    value={password}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
                    autoComplete="current-password"
                    required
                    placeholder="Enter your password"
                    disabled={isLoading}
                  />
                </div>
              </div>

              {error && (
                <Alert variant="destructive">
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              <Button 
                type="submit" 
                className="w-full" 
                disabled={isLoading}
              >
                {isLoading ? (
                  <div className="flex items-center space-x-2">
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    <span>Signing in...</span>
                  </div>
                ) : (
                  'Sign in'
                )}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>

      {/* Right side - Background/Branding */}
      <div className="hidden lg:block lg:w-1/2 bg-gradient-to-br from-blue-500 to-indigo-600">
        <div className="h-full flex items-center justify-center p-12">
          <div className="text-white text-center space-y-6">
            <div className="w-24 h-24 mx-auto bg-white/20 rounded-3xl flex items-center justify-center backdrop-blur-sm">
              <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-4m-5 0H3m2 0v-3.75M3 21v-6a2 2 0 012-2h6.5m3 0V9a2 2 0 012-2h1M21 8.5v2.75m-3 0V21m-4-3h2m-2-3h2m-2-3h2m-2-3h2M7 8h2m-2 4h2m-2 4h2m-2 4h2"/>
              </svg>
            </div>
            <div>
              <h1 className="text-4xl font-bold mb-4">UrbanAI Platform</h1>
              <p className="text-xl opacity-90 max-w-md">
                Empowering sustainable urban development through AI-driven analytics and insights.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// urbanai-app/src/pages/LoginPage.vue
<template>
  <div class="min-h-screen flex">
    <!-- Left side - Login form -->
    <div class="flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8">
      <div class="max-w-md w-full space-y-8">
        <div class="text-center">
          <h2 class="text-3xl font-bold text-gray-900 dark:text-white">
            Welcome to DeCO<sub class="text-2xl">two</sub>
          </h2>
          <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
            Sign in to your account to continue
          </p>
        </div>

        <form class="mt-8 space-y-6" @submit.prevent="handleLogin">
          <div class="space-y-4">
            <div>
              <Label for="username">Username</Label>
              <Input
                id="username"
                v-model="username"
                type="text"
                autocomplete="username"
                required
                placeholder="Enter your username"
                :disabled="isLoading"
              />
            </div>

            <div>
              <Label for="password">Password</Label>
              <Input
                id="password"
                v-model="password"
                type="password"
                autocomplete="current-password"
                required
                placeholder="Enter your password"
                :disabled="isLoading"
              />
            </div>
          </div>

          <div v-if="error" class="text-sm text-red-600 dark:text-red-400">
            {{ error }}
          </div>

          <Button
            type="submit"
            class="w-full"
            :disabled="isLoading"
          >
            <div v-if="isLoading" class="flex items-center justify-center">
              <div class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
              Signing in...
            </div>
            <span v-else>Sign in</span>
          </Button>
        </form>

        <div class="text-center">
          <p class="text-xs text-gray-500 dark:text-gray-400">
            By signing in, you agree to our 
            <a href="#" class="text-blue-600 hover:text-blue-500 dark:text-blue-400">Terms of Service</a> 
            and 
            <a href="#" class="text-blue-600 hover:text-blue-500 dark:text-blue-400">Privacy Policy</a>
          </p>
        </div>
      </div>
    </div>

    <!-- Right side - Background/Image -->
    <div class="hidden lg:flex lg:flex-1 lg:relative bg-black">
      <div class="absolute top-4 right-4">
        <img src="@/assets/deco_two_logo.svg" alt="DeCOtwo Logo" class="h-12 w-auto filter brightness-0 invert" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useDecotwoAuth } from '@/composables/useDecotwoAuth'

const { login, isLoading, error } = useDecotwoAuth()

// Form data
const username = ref('')
const password = ref('')

const handleLogin = async () => {
  if (!username.value || !password.value) return
  
  await login({
    username: username.value,
    password: password.value
  })
}
</script>
